entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: https
  websecure:
    address: ":443"


  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "etc/traefik/config"
    watch: true
api: {}

certificatesResolvers:
  mycertresolver:
    acme: 
         email: "xxx"
         storage: "/etc/traefik/traefik_letsencrypt/traefik_letsencrypt.json"
         httpChallenge:
          entryPoint: "websecure"
